# Generated by Django 4.1.1 on 2022-09-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldvaluethrough',
            old_name='form',
            new_name='value',
        ),
    ]
