# Generated by Django 4.1.1 on 2022-09-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_rename_form_fieldvaluethrough_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'Field')), models.Q(('app_label', 'core'), ('model', 'Value')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='contenttypes.contenttype', verbose_name='Depends On Object'),
        ),
        migrations.AlterField(
            model_name='field',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='field',
            name='file_types',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Allow File Types'),
        ),
        migrations.AlterField(
            model_name='field',
            name='object_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Depends on Object ID'),
        ),
    ]
