# Generated by Django 4.1.1 on 2022-09-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_alter_field_content_type_alter_field_file_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ('weight',), 'verbose_name': 'Value', 'verbose_name_plural': 'Values'},
        ),
        migrations.AlterField(
            model_name='field',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'field')), models.Q(('app_label', 'core'), ('model', 'value')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='contenttypes.contenttype', verbose_name='Depends On Object'),
        ),
        migrations.AlterField(
            model_name='formdetail',
            name='limit_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Limit Submiting Form'),
        ),
        migrations.AlterField(
            model_name='formdetail',
            name='mail_message',
            field=models.TextField(blank=True, help_text='You can use form fields name in this box eg: {{field_name}} or {{form_data}} to send all user data', null=True, verbose_name='Mail Message'),
        ),
    ]
