# Generated by Django 4.1.1 on 2022-09-17 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_value_options_alter_field_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdetail',
            name='template',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='core.formtemplate', verbose_name='Template'),
        ),
    ]
