# Generated by Django 4.1.1 on 2022-09-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_formapimanager_show_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='limit_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Limit Submiting Form'),
        ),
        migrations.AddField(
            model_name='form',
            name='redirect_url',
            field=models.URLField(blank=True, null=True, verbose_name='Redirect URL'),
        ),
        migrations.AddField(
            model_name='form',
            name='submit_text',
            field=models.CharField(default='Submit', max_length=100, verbose_name='Submit Text'),
        ),
        migrations.AddField(
            model_name='form',
            name='success_message',
            field=models.CharField(default='success', max_length=255, verbose_name='Success Message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='template',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='core.formtemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='form',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid From'),
        ),
        migrations.AddField(
            model_name='form',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid To'),
        ),
        migrations.DeleteModel(
            name='FormDetail',
        ),
    ]
