# Generated by Django 4.1.1 on 2022-09-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_form_limit_to_form_redirect_url_form_submit_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='success_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Success Message'),
        ),
    ]
