# Generated by Django 4.1.1 on 2022-09-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_formapimanager_show_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldthrough',
            name='position',
            field=models.CharField(choices=[('inline', 'In-line'), ('inorder', 'In-Order')], default='inline', max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='fieldcategory',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
    ]
