# Generated by Django 4.1.1 on 2022-09-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_formfieldthrough_position_alter_fieldcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldthrough',
            name='position',
            field=models.CharField(choices=[('inline', 'In-line'), ('inorder', 'In-Order'), ('break', 'Break')], default='break', max_length=100, verbose_name='Position'),
        ),
    ]
