# Generated by Django 4.1.1 on 2022-09-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_formfieldthrough_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='category',
        ),
        migrations.AddField(
            model_name='formfieldthrough',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_field_through', to='core.fieldcategory', verbose_name='Category'),
        ),
    ]
