# Generated by Django 4.1.1 on 2023-02-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_form_generator', '0005_alter_field_genre_alter_fieldvalidator_validator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldvalidator',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='fieldvalidator',
            constraint=models.UniqueConstraint(fields=('field', 'validator'), name='field_validator_unique'),
        ),
        migrations.AddConstraint(
            model_name='formfieldthrough',
            constraint=models.UniqueConstraint(fields=('field', 'form'), name='form_field_unique'),
        ),
    ]
